model:
  name: 'model.recurrent_norm.Model'
  args:
    fft_size: 512
    hop_size: 256
    rnn_cell_type: 'GRU'
    norm_rnn_cell_size: 16
    norm_rnn_layers: 2
    rnn_cell_size: 64
    rnn_layers: 1

loss:
  name: 'loss.sdr.Loss'
  args:
    fft_size: 512
    hop_size: 256

dataset:
  train:
    name: 'dataset.near_field.Dataset'
    args:
      # enorm: False
      chunk_size: 4
      # samplerate: 16000
      clean:
        - /local/data/6500h.lmdb
      noise:
        /local/data/wind-noise.lmdb:
          prob: 0.5
          snr: [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]
        /local/data/wind-noise-record.lmdb:
          prob: 0.5
          snr: [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]
        /local/data/n40k-ly.lmdb:
          prob: 0.5
          snr: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 25]
        # /local/data/inoise.lmdb:
        #   prob: 2
        #   snr: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 25]
        /local/data/pnoise.flac:
          prob: 3
          snr: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 25]
        /local/data/bbc.lmdb:
          prob: 3
          snr: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 25]
        /local/data/dns.lmdb:
          prob: 3
          snr: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 25]
  dev:
    name: 'dataset.devset_npy.Dataset'
    args:
      enorm: False
      dev_dir: '/local/data/dev_set'

transform:
  name: 'transform.pcm_int16.Transform'
  args:
    hop_size: 256
  collate_fn:
    name: 'transform.pcm_int16.collate_fn'

train:
  gpu_ids: 4, 5
  num_epochs: 40
  dataloader:
    shuffle: False
    batch_size: 128
    num_workers: 16
  optimizer:
    name: 'torch.optim.Adam'
    args:
      weight_decay: 0.000001

eval:
  dataloader:
    shuffle: False
    batch_size: 8
    num_workers: 16
  evaluator:
    name: 'evaluate.stoi_pesq.Evaluator'
    num_workers: 32

checkpoint:
  './checkpoint/nf'

visdom:
  ip: '10.160.82.54'
  port: 8899
